version: "3.7"

services:

  ModernPHP:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - modernphp

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8030:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
     - modernphp

  db:
   image: mysql:5.7
   restart: unless-stopped
   environment:
     MYSQL_DATABASE: modernphp
     MYSQL_ROOT_PASSWORD: 123456$Aa
     SERVICE_TAGS: dev
     SERVICE_NAME: mysql
   ports:
    - '3306:3306'
   volumes:
     - ./docker-compose/db_data:/var/lib/mysql
   networks:
    - modernphp


  phpmyadmin:
   depends_on:
     - db
   image: phpmyadmin/phpmyadmin
   restart: always
   ports:
     - '8040:80'
   environment:
     PMA_HOST: db
   networks:
    - modernphp

networks:
  modernphp:
